plugins {
    id 'java'
    id 'application'
}

group = 'dev.hudson.validator'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'dev.hudson.validator.Main'
}
repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}